fatal error in ProElement v4.0.4 due to missing utils.php
Commented out the high tier check in add_actions method.

Fatal error: Uncaught Error: Class "ElementorPro\Core\App\Modules\ImportExportCustomization\Utils" not found in /home/mydomain/public_html/wp-content/plugins/pro-elements/core/app/modules/import-export-customization/module.php:37 

Stack trace:
 #0 /home/mydomain/public_html/wp-content/plugins/pro-elements/core/app/modules/import-export-customization/module.php(33): ElementorPro\Core\App\Modules\ImportExportCustomization\Module->add_actions()
 #1 /home/mydomain/public_html/wp-content/plugins/pro-elements/core/app/app.php(146): ElementorPro\Core\App\Modules\ImportExportCustomization\Module->__construct()
 #2 /home/mydomain/public_html/wp-content/plugins/pro-elements/plugin.php(471): ElementorPro\Core\App\App->__construct()
 #3 /home/mydomain/public_html/wp-content/plugins/pro-elements/plugin.php(135): ElementorPro\Plugin->__construct()
 #4 /home/mydomain/public_html/wp-content/plugins/pro-elements/plugin.php(528): ElementorPro\Plugin::instance()
 #5 /home/mydomain/public_html/wp-content/plugins/pro-elements/pro-elements.php(78): require('/home/mydomain...')
 #6 /home/mydomain/public_html/wp-includes/class-wp-hook.php(341): pro_elements_load_plugin_func()
 #7 /home/mydomain/public_html/wp-includes/class-wp-hook.php(365): WP_Hook->apply_filters()
 #8 /home/mydomain/public_html/wp-includes/plugin.php(522): WP_Hook->do_action()
 #9 /home/mydomain/public_html/wp-settings.php(593): do_action()
 #10 /home/mydomain/wp-config.php(99): require_once('/home/mydomain...')
 #11 /home/mydomain/public_html/wp-load.php(55): require_once('/home/mydomain...')
 #12 /home/mydomain/public_html/wp-admin/admin.php(35): require_once('/home/mydomain...')
 #13 /home/mydomain/public_html/wp-admin/plugins.php(10): require_once('/home/mydomain...')
 #14 {main} thrown in /home/mydomain/public_html/wp-content/plugins/pro-elements/core/app/modules/import-export-customization/module.php on line 37